version: 2

sources:
  - name: databird_final_project
    schema: databird_final_project
    tables:
      - name: brands 
      - name: categories 
      - name: customers 
      - name: order_items 
      - name: orders 
      - name: products 
      - name: staffs 
      - name: stocks 
      - name: stores 

      
  