version: 1

models:
    - name: mrt_daily_revenues_per_store_seller
      description: this tables tracks daily revenues made by each seller in all stores
      columns:
          - name: order_date
            description: date the order was created
            tests:
              - not_null
            